### ISSUE TITLE
Power saving proposal: reduce cpu frequency

### ISSUE THREAD

**Issue by IU5HKU** [SensorsIot/DCF77-Transmitter-for-ESP32#11]
This isn't an issue, your code works great, my old oregon scientific clock is rebirth :-)
I'm using this code with a battery operated esp32 who sits near the clock, with 4 NiMh batteries (i know, it's not the best, but it's a zero-cost project and i've used things that i had in my junkyard, i'm using an old ferrite antenna from another dead clock...). To maximize batteries life i've reduced the cpu frequency with this code into setup():

  if(setCpuFrequencyMhz(80)){
    Serial.print("CPU frequency set @");
    Serial.print(getCpuFrequencyMhz());
    Serial.println("Mhz");
  }
  else
    Serial.println("Fail to set cpu frequency");

...why not add this to your code... :-)
Have a nice day
 MC

**Comment by deltazerorsan** [comment]
> This isn't an issue, your code works great, my old oregon scientific clock is rebirth :-) I'm using this code with a battery operated esp32 who sits near the clock, with 4 NiMh batteries (i know, it's not the best, but it's a zero-cost project and i've used things that i had in my junkyard, i'm using an old ferrite antenna from another dead clock...). To maximize batteries life i've reduced the cpu frequency with this code into setup():
> 
> if(setCpuFrequencyMhz(80)){ Serial.print("CPU frequency set @"); Serial.print(getCpuFrequencyMhz()); Serial.println("Mhz"); } else Serial.println("Fail to set cpu frequency");
> 
> ...why not add this to your code... :-) Have a nice day MC

Hi,

Are you using all the features about timing the periods of transmission?

There is a few nice features to save power...

**Comment by IU5HKU** [comment]
Sure, i'm using the cron feature, using only one time window at 24:00, and works as expected. I know, only ten minutes at day, but reducing cpu frequency is effortless and contribute to long lasting the batteries (in my case).

**Comment by deltazerorsan** [comment]
Nice to hear that!

**Comment by SensorsIot** [comment]
Done. Thank you!
