### ISSUE TITLE
Antenna...??? 

### ISSUE THREAD

**Issue by PinoS56** [SensorsIot/DCF77-Transmitter-for-ESP32#5]
Hi Andreas,
I need help, I have compiled the firmware, but the data does not show how the antenna must be, any hypotheses ... a coil on ferrite ...? coil in the air ...? how should it be connected to the ESP32 directly to the pin, or there is a resistor ...?
I thank you in advance
Best regards Pino ...

**Comment by SensorsIot** [comment]
I thought I showed how I built mine in video #287
