### ISSUE TITLE
'ESP_SLEEP_WAKEUP_ALL' was not declared in this scope

### ISSUE THREAD

**Issue by tiagofreire-pt** [SensorsIot/DCF77-Transmitter-for-ESP32#6]
Hi.

I'm compiling this code for the Wemos D1 mini and results on this error.

But compiles fine to the ESP32 Wrover.

Am I missing something?

Thanks.

**Comment by deltazerorsan** [comment]
Hi,

The Wemos D1 mini is not a ESP32 (in my understanding) it is an ESP8266...
